name: Test NWB Data Viewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        python -c "import dash, plotly, numpy, pandas, scipy, h5py, pynwb; print('All imports successful')"
    
    - name: Check code syntax
      run: |
        python -m py_compile nwb_data_viewer.py
        echo "Syntax check passed"
